name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Setup Docker on VPS"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy Docker container to VPS
      - name: Deploy Docker container to VPS
        run: |
          echo "Starting SSH connection to VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e 
            echo "Stopping existing Docker container if any..."
            docker stop react-crm || true
            docker rm react-crm || true

            echo "Pulling the latest Docker image..."
            docker pull lucaszub/react-crm:latest

            echo "Running the Docker container..."
            docker run -d -p 80:80 lucaszub/react-crm:latest

            echo "Deployment completed successfully!"
          EOF

      # Verify Deployment Status
      - name: Verify Deployment Status
        run: |
          echo "Checking Docker container status on VPS..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            docker ps | grep react-crm || echo "Docker container is not running"
          EOF
