name: Docker Publish

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser une machine Ubuntu pour le build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Utilisation de la dernière version stable de checkout

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Installer Docker Buildx pour les builds multiplateformes

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  #  Se connecter à Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation du secret pour le nom d'utilisateur Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Utilisation du secret pour le mot de passe Docker Hub

    - name: Build and push Docker image
      uses: docker/build-push-action@v2  # Action pour construire et pousser l'image Docker
      with:
        context: .  # Dossier contenant votre Dockerfile (ici, le répertoire racine)
        push: true  # Indiquer que l'image doit être poussée vers Docker Hub
        tags: lucaszub/react-crm:latest  # Le tag fixe pour l'image Docker
